version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secure
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./data:/data

volumes:
  pgdata:
    driver: local
